### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kdyoung100** [phac-nml/sistr_cmd#54]
./sistr 
Traceback (most recent call last):
  File "./sistr", line 7, in <module>
    from sistr.sistr_cmd import main
  File "/home/tools/anaconda3/lib/python3.7/site-packages/sistr/sistr_cmd.py", line 14, in <module>
    from sistr.src.blast_wrapper import BlastRunner
  File "/home/tools/anaconda3/lib/python3.7/site-packages/sistr/src/blast_wrapper/__init__.py", line 9, in <module>
    from pandas.io.common import EmptyDataError
ImportError: cannot import name 'EmptyDataError' from 'pandas.io.common' (/home/tools/anaconda3/lib/python3.7/site-packages/pandas/io/common.py)

**Comment by kbessonov1984** [comment]
Yes, please downgrade pandas to version 1.0.5. The EmptyDataFrame class was
moved in superior versions. Next release of SISTR will make it compatible
with the newest pandas versions. The conda recipe indeed limits pandas
version for the very same reason.
