### ISSUE TITLE
sistr 1.1.3 uses pkg_resource that is deprecated

### ISSUE THREAD

**Issue by atks** [phac-nml/sistr_cmd#61]
Encountered some issues when installing commandline sistr via pip on Ubuntu Noble Numbat.

sistr-1.1.3/bin/sistr
Traceback (most recent call last):
  File "/home/atks/sistr-1.1.3/bin/sistr", line 5, in <module>
    from sistr.sistr_cmd import main
  File "/home/atks/sistr-1.1.3/lib/python3.12/site-packages/sistr/sistr_cmd.py", line 10, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'

Is it possible to update the egg mechanism?

https://github.com/pypa/pip/issues/12330

**Comment by kbessonov1984** [comment]
This issue is easily solvable after install of setuptools by running pip install setuptools command

**Comment by KasperThystrup** [comment]
Installation through micromamba will succeed, but all use of sistr will lead to same error. If going with clean environment, using older versions of python might force setuptools to install an old version.
